# Generated by Django 3.0.2 on 2020-02-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200204_0126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrelation',
            unique_together={('follower', 'followed')},
        ),
    ]
