# Generated by Django 3.0.2 on 2020-02-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200204_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='_comment_replies_+', to='login.Comment'),
        ),
    ]
